from __future__ import annotations

import time
import logging
from openai import AsyncOpenAI
from modora.core.settings import Settings
from modora.core.infra.llm.base import BaseAsyncLLMClient


class AsyncRemoteLLMClient(BaseAsyncLLMClient):
    """Asynchronous remote LLM client, inherited from BaseAsyncLLMClient.

    Specifically used for calling remote OpenAI compatible interfaces (e.g., Gemini, GPT, etc.).
    """

    def __init__(self, settings: Settings | None = None, instance_id: str | None = None):
        """Initialize remote client.

        Args:
            settings: Configuration object. If None, default configuration is loaded.
            instance_id: Optional specific model instance ID to use.
        """
        super().__init__(settings, instance_id=instance_id)
        self._init_client()

    def _init_client(self):
        """Initialize OpenAI async client instance based on configuration."""
        # Use explicit instance if provided
        if self.instance_id:
            instance = self.settings.resolve_model_instance(self.instance_id)
            if instance and instance.type == "remote":
                self.api_key = instance.api_key
                self.base_url = instance.base_url
                self.model = instance.model or "gemini-2.5-flash"
            else:
                self.api_key = None
                self.base_url = None
                self.model = "gemini-2.5-flash"
        else:
            # Fallback (though global fields are mostly gone)
            self.api_key = getattr(self.settings, "api_key", None)
            self.base_url = getattr(self.settings, "api_base", None)
            self.model = getattr(self.settings, "api_model", "gemini-2.5-flash")

        if self.api_key and self.base_url:
            self.client = AsyncOpenAI(
                api_key=self.api_key,
                base_url=self.base_url,
                timeout=float(getattr(self.settings, "llm_request_timeout_s", 60.0)),
            )
        else:
            self.client = None

    async def _call_llm(
        self, prompt: str, base64_image: str | list[str] | None = None
    ) -> str:
        """Implement abstract method to call remote LLM interface.

        Supports sending text prompt and multiple Base64 encoded images.

        Args:
            prompt: Prompt text.
            base64_image: Base64 encoded string(s) of image(s).

        Returns:
            Text response content generated by the model.
        """
        if not self.client:
            logging.getLogger(__name__).error(
                "Remote LLM client not initialized (missing api_key or api_base)"
            )
            raise RuntimeError("remote llm client not initialized")

        messages = [
            {
                "role": "user",
                "content": [
                    {"type": "text", "text": prompt},
                ],
            }
        ]

        if base64_image:
            if isinstance(base64_image, str):
                base64_image = [base64_image]

            for img in base64_image:
                # Only process if img looks like Base64 (no spaces and sufficient length)
                if isinstance(img, str) and len(img) > 100 and " " not in img:
                    img = img.strip()
                    padding = len(img) % 4
                    if padding > 0:
                        img += "=" * (4 - padding)

                    messages[0]["content"].append(
                        {
                            "type": "image_url",
                            "image_url": {"url": f"data:image/jpeg;base64,{img}"},
                        }
                    )

        logger = logging.getLogger(__name__)
        started_at = time.monotonic()
        logger.info(
            "Remote LLM request start",
            extra={
                "model": self.model,
                "base_url": self.base_url,
                "message_parts": len(messages[0]["content"]),
                "has_image": len(messages[0]["content"]) > 1,
                "prompt_chars": len(prompt),
                "timeout_s": float(getattr(self.settings, "llm_request_timeout_s", 60.0)),
            },
        )

        try:
            response = await self.client.chat.completions.create(
                model=self.model,
                messages=messages,
                max_completion_tokens=16384,  # Increase token limit to support long text generation
            )
            content = response.choices[0].message.content or ""
            logger.info(
                "Remote LLM request success",
                extra={
                    "model": self.model,
                    "duration_s": round(time.monotonic() - started_at, 3),
                    "response_chars": len(content),
                },
            )
            return content
        except Exception as e:
            logger.error(
                "Remote LLM call failed",
                extra={
                    "model": self.model,
                    "base_url": self.base_url,
                    "duration_s": round(time.monotonic() - started_at, 3),
                    "error": str(e),
                },
            )
            raise
