import argparse
import asyncio
import json
import logging
import os
from pathlib import Path
from typing import List

import Levenshtein
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from tqdm import tqdm

from modora.core.domain.results import ResultItem, write_results_file
from modora.core.infra.llm import (
    AsyncLocalLLMClient,
    AsyncRemoteLLMClient,
    ensure_llm_local_loaded,
    shutdown_llm_local,
)
from modora.core.settings import Settings


class Evaluator:
    """评估器类，用于判断生成的答案是否正确"""

    def __init__(
        self, settings: Settings, logger: logging.Logger, use_remote: bool = False
    ):
        self.settings = settings
        self.logger = logger
        if use_remote:
            self.llm = AsyncRemoteLLMClient(settings)
        else:
            self.llm = AsyncLocalLLMClient()

    async def check_answer(self, query: str, answer: str) -> bool:
        """检查回答是否有效"""
        try:
            return await self.llm.check_answer(query, answer)
        except Exception as e:
            self.logger.error(f"Error in check_answer: {e}")
            return False

    async def is_equal(self, query: str, references: List[str], prediction: str) -> str:
        """判断预测答案是否与参考答案等价"""
        if not prediction:
            return "F"

        for reference in references:
            # 包含性检查：如果参考答案包含在预测中，则认为正确
            if reference.lower() in prediction.lower():
                return "T"

            # AI 辅助检查：使用 LLM 判断语义是否一致
            try:
                if await self.llm.evaluate(query, reference, prediction):
                    return "T"
            except Exception as e:
                self.logger.error(f"Error in is_equal AI check: {e}")

        return "F"

    def anls_single_sample(
        self, prediction: str, references: List[str], threshold: float = 0.5
    ) -> float:
        """计算单个样本的 ANLS (Average Normalized Levenshtein Similarity) 分数"""
        max_nls = 0.0
        pred_str = prediction if prediction is not None else ""

        for reference in references:
            distance = Levenshtein.distance(pred_str, reference)
            max_len = max(len(pred_str), len(reference))
            if max_len == 0:
                nls = 1.0
            else:
                nls = 1.0 - float(distance) / max_len

            if nls > max_nls:
                max_nls = nls

        return max_nls if max_nls > threshold else 0.0


def register(sub: argparse._SubParsersAction) -> None:
    """注册 evaluate 子命令"""
    parser = sub.add_parser("evaluate", help="Evaluate QA results")
    parser.add_argument(
        "--input",
        default="/home/yukai/project/MoDora/datasets/MMDA/test.json",
        help="Path to the input JSON file (original dataset)",
    )
    parser.add_argument(
        "--result",
        default="/home/yukai/project/MoDora/MoDora-backend/tmp/result.json",
        help="Path to the result JSON file (generated by batch-qa)",
    )
    parser.add_argument(
        "--output",
        help="Path to save the evaluation report (JSONL) (default: same as --input with .jsonl extension)",
    )
    parser.add_argument(
        "--analyze",
        action="store_true",
        default=True,
        help="Whether to analyze the results and generate charts (default: True)",
    )
    parser.add_argument(
        "--concurrency",
        type=int,
        default=16,
        help="Max concurrent evaluation tasks",
    )
    parser.add_argument(
        "--remote",
        action="store_true",
        help="Use remote LLM defined in local.json for evaluation",
    )
    parser.set_defaults(_handler=_handle_evaluate)


async def _process_single_item(
    item: dict, prediction_map: dict, evaluator: Evaluator, sem: asyncio.Semaphore
) -> ResultItem | None:
    """处理单个评估项"""
    async with sem:
        try:
            qid = item.get("questionId")
            if qid not in prediction_map:
                # 缺少预测结果
                return None

            pred_item = prediction_map[qid]
            prediction = pred_item.get("prediction")

            # 准备参考答案列表
            answer = item.get("answer", [])
            if isinstance(answer, str):
                answer = [answer]
            elif not isinstance(answer, list):
                # 针对复杂数据集（如 DUDE）的回退逻辑
                if "answers" in item:
                    answer = [", ".join(item["answers"])] + item.get(
                        "answers_variants", []
                    )
                else:
                    answer = []

            # AI 判定
            judge = "F"

            # 针对不可回答问题的特殊逻辑
            if item.get("answer_type") == "not-answerable":
                is_valid_ans = await evaluator.check_answer(
                    item["question"], prediction
                )
                if not is_valid_ans:
                    judge = "T"
                else:
                    judge = "F"
            else:
                judge = await evaluator.is_equal(item["question"], answer, prediction)

            # 构造 ResultItem
            result_item = ResultItem(
                questionId=qid,
                pdf_id=item.get("pdf_id", "")
                or str(item.get("image_id", "")),  # 回退到 image_id
                question=item["question"],
                answer=answer,
                tag=item.get("tag"),
                prediction=prediction,
                judge=judge,
            )
            return result_item

        except Exception as e:
            evaluator.logger.error(
                f"Error processing item {item.get('questionId')}: {e}"
            )
            return None


async def _run_evaluation(
    input_path: Path,
    result_path: Path,
    output_path: Path,
    concurrency: int,
    logger: logging.Logger,
    use_remote: bool = False,
):
    """运行批量评估流程"""
    settings = Settings.load()
    evaluator = Evaluator(settings, logger, use_remote=use_remote)

    # 加载数据集和预测结果
    with open(input_path, "r", encoding="utf-8") as f:
        dataset = json.load(f)

    with open(result_path, "r", encoding="utf-8") as f:
        results = json.load(f)

    # 将预测结果按 ID 映射，以便快速查找
    prediction_map = {r["questionId"]: r for r in results}

    sem = asyncio.Semaphore(concurrency)
    tasks = [
        _process_single_item(item, prediction_map, evaluator, sem) for item in dataset
    ]

    evaluated_items = []
    for f in tqdm(asyncio.as_completed(tasks), total=len(tasks), desc="Evaluating"):
        res = await f
        if res:
            evaluated_items.append(res)

    # 保存评估结果
    output_path.parent.mkdir(parents=True, exist_ok=True)
    write_results_file(str(output_path), evaluated_items)

    # 计算各项指标
    total = len(evaluated_items)
    correct = sum(1 for item in evaluated_items if item.judge == "T")
    accuracy = correct / total if total > 0 else 0.0

    anls_score = 0.0
    for item in evaluated_items:
        if item.judge == "T":

            contain = False
            if item.prediction:
                for ans in item.answer:
                    if ans and ans.lower() in item.prediction.lower():
                        contain = True
                        break

            if contain:
                anls_score += 1.0
            elif item.answer == [] or (
                item.prediction is None and item.judge == "T"
            ):  # 针对不可回答问题的近似处理
                anls_score += 1.0
            else:
                anls_score += evaluator.anls_single_sample(item.prediction, item.answer)
        else:
            anls_score += evaluator.anls_single_sample(item.prediction, item.answer)

    anls = anls_score / total if total > 0 else 0.0

    print("\nEvaluation Complete.")
    print(f"Total: {total}")
    print(f"Accuracy: {accuracy:.4f}")
    print(f"ANLS: {anls:.4f}")
    print(f"Detailed results saved to {output_path}")

    return evaluated_items


def _plot_results(evaluated_items: List[ResultItem], output_dir: Path):
    """根据评估结果生成图表和汇总 CSV"""
    if not evaluated_items:
        print("No data to plot.")
        return

    data = []
    for item in evaluated_items:
        tag = item.tag or "Unknown"
        category = "Unknown"
        if isinstance(tag, str) and "-" in tag:
            try:
                # 按照 analyze_eval.py 的逻辑，取连字符后的部分
                category = tag.split("-")[-1]
            except Exception:
                pass

        # 计算 ACNLS (包含性检查 + ANLS)
        acnls = 0.0
        contain = False
        pred_str = str(item.prediction).lower() if item.prediction is not None else ""

        if item.answer:
            for ans in item.answer:
                ans_str = str(ans).lower()
                if ans_str and ans_str in pred_str:
                    contain = True
                    break

        if contain:
            acnls = 1.0
        else:
            # 这里的 ANLS 计算逻辑复用 Evaluator 中的实现，但使用 threshold=0.5
            # analyze_eval.py 中使用了 0.5 的阈值
            max_nls = 0.0
            for ref in item.answer:
                ref_str = str(ref).lower()
                dist = Levenshtein.distance(pred_str, ref_str)
                max_len = max(len(pred_str), len(ref_str))
                nls = 1.0 - (dist / max_len) if max_len > 0 else 1.0
                max_nls = max(max_nls, nls)
            acnls = max_nls if max_nls > 0.5 else 0.0

        data.append(
            {
                "tag": tag,
                "category": category,
                "Accuracy": 1.0 if item.judge == "T" else 0.0,
                "ACNLS": acnls,
            }
        )

    df = pd.DataFrame(data)
    output_dir.mkdir(parents=True, exist_ok=True)

    # 分组统计
    grouped = df.groupby("tag")[["Accuracy", "ACNLS"]].mean().reset_index()
    grouped = grouped.sort_values("tag")

    sns.set_theme(style="whitegrid")

    # 1. Plot Accuracy per Tag
    plt.figure(figsize=(12, 6))
    ax = sns.barplot(
        x="tag", y="Accuracy", data=grouped, hue="tag", palette="viridis", legend=False
    )
    plt.title("Accuracy per Tag", fontsize=16)
    plt.ylim(0, 1.1)
    for p in ax.patches:
        ax.annotate(
            f"{p.get_height():.2f}",
            (p.get_x() + p.get_width() / 2.0, p.get_height()),
            ha="center",
            va="center",
            xytext=(0, 9),
            textcoords="offset points",
        )
    plt.tight_layout()
    plt.savefig(output_dir / "accuracy_per_tag.png")
    plt.close()

    # 2. Plot ACNLS per Tag
    plt.figure(figsize=(12, 6))
    ax = sns.barplot(
        x="tag", y="ACNLS", data=grouped, hue="tag", palette="magma", legend=False
    )
    plt.title("ACNLS per Tag", fontsize=16)
    plt.ylim(0, 1.1)
    for p in ax.patches:
        ax.annotate(
            f"{p.get_height():.2f}",
            (p.get_x() + p.get_width() / 2.0, p.get_height()),
            ha="center",
            va="center",
            xytext=(0, 9),
            textcoords="offset points",
        )
    plt.tight_layout()
    plt.savefig(output_dir / "acnls_per_tag.png")
    plt.close()

    # 3. Save Summaries
    grouped.to_csv(output_dir / "metrics_summary_by_tag.csv", index=False)

    category_grouped = df.groupby("category")[["Accuracy", "ACNLS"]].mean().reset_index()
    category_grouped = category_grouped.sort_values("category")
    category_grouped.to_csv(output_dir / "metrics_summary_by_category.csv", index=False)

    # 4. Plot Category Metrics
    for metric in ["Accuracy", "ACNLS"]:
        plt.figure(figsize=(10, 6))
        palette = "viridis" if metric == "Accuracy" else "magma"
        ax = sns.barplot(
            x="category",
            y=metric,
            data=category_grouped,
            hue="category",
            palette=palette,
            legend=False,
        )
        plt.title(f"{metric} per Category", fontsize=16)
        plt.ylim(0, 1.1)
        for p in ax.patches:
            ax.annotate(
                f"{p.get_height():.2f}",
                (p.get_x() + p.get_width() / 2.0, p.get_height()),
                ha="center",
                va="center",
                xytext=(0, 9),
                textcoords="offset points",
            )
        plt.tight_layout()
        plt.savefig(output_dir / f"{metric.lower()}_per_category.png")
        plt.close()

    print(f"\nAnalysis results (charts and CSVs) saved to {output_dir}")
    print("\nSummary by Tag:")
    print(grouped)
    print("\nSummary by Category:")
    print(category_grouped)
    print("\nOverall Metrics:")
    print(df[["Accuracy", "ACNLS"]].mean())


def _handle_evaluate(args: argparse.Namespace, logger: logging.Logger) -> int:
    """evaluate 命令的处理器"""
    # 只有在不使用远程 LLM 时才确保本地 LLM 已加载
    if not args.remote:
        ensure_llm_local_loaded(Settings.load(), logger)
    try:
        input_path = Path(args.input)
        output_path = (
            Path(args.output)
            if args.output
            else input_path.with_suffix(".jsonl")
        )

        evaluated_items = asyncio.run(
            _run_evaluation(
                input_path,
                Path(args.result),
                output_path,
                args.concurrency,
                logger,
                use_remote=args.remote,
            )
        )

        if args.analyze:
            _plot_results(evaluated_items, output_path.parent)

        return 0
    except Exception as e:
        logger.error(f"Evaluation failed: {e}")
        return 1
    finally:
        if not args.remote:
            shutdown_llm_local()
