import argparse
import asyncio
import json
import logging
from pathlib import Path
from typing import List

import Levenshtein
from tqdm import tqdm

from modora.core.domain.results import ResultItem, write_results_file
from modora.core.infra.llm import (
    AsyncLocalLLMClient,
    AsyncRemoteLLMClient,
    ensure_llm_local_loaded,
    shutdown_llm_local,
)
from modora.core.settings import Settings


class Evaluator:
    """评估器类，用于判断生成的答案是否正确"""

    def __init__(
        self, settings: Settings, logger: logging.Logger, use_remote: bool = False
    ):
        self.settings = settings
        self.logger = logger
        if use_remote:
            self.llm = AsyncRemoteLLMClient(settings)
        else:
            self.llm = AsyncLocalLLMClient()

    async def check_answer(self, query: str, answer: str) -> bool:
        """检查回答是否有效"""
        try:
            return await self.llm.check_answer(query, answer)
        except Exception as e:
            self.logger.error(f"Error in check_answer: {e}")
            return False

    async def is_equal(self, query: str, references: List[str], prediction: str) -> str:
        """判断预测答案是否与参考答案等价"""
        if not prediction:
            return "F"

        for reference in references:
            # 包含性检查：如果参考答案包含在预测中，则认为正确
            if reference.lower() in prediction.lower():
                return "T"

            # AI 辅助检查：使用 LLM 判断语义是否一致
            try:
                if await self.llm.evaluate(query, reference, prediction):
                    return "T"
            except Exception as e:
                self.logger.error(f"Error in is_equal AI check: {e}")

        return "F"

    def anls_single_sample(
        self, prediction: str, references: List[str], threshold: float = 0.5
    ) -> float:
        """计算单个样本的 ANLS (Average Normalized Levenshtein Similarity) 分数"""
        max_nls = 0.0
        pred_str = prediction if prediction is not None else ""

        for reference in references:
            distance = Levenshtein.distance(pred_str, reference)
            max_len = max(len(pred_str), len(reference))
            if max_len == 0:
                nls = 1.0
            else:
                nls = 1.0 - float(distance) / max_len

            if nls > max_nls:
                max_nls = nls

        return max_nls if max_nls > threshold else 0.0


def register(sub: argparse._SubParsersAction) -> None:
    """注册 evaluate 子命令"""
    parser = sub.add_parser("evaluate", help="Evaluate QA results")
    parser.add_argument(
        "--input",
        default="/home/yukai/project/MoDora/datasets/MMDA/test.json",
        help="Path to the input JSON file (original dataset)",
    )
    parser.add_argument(
        "--result",
        default="/home/yukai/project/MoDora/MoDora-backend/tmp/result.json",
        help="Path to the result JSON file (generated by batch-qa)",
    )
    parser.add_argument(
        "--output",
        default="/home/yukai/project/MoDora/MoDora-backend/tmp/evaluation.jsonl",
        help="Path to save the evaluation report (JSONL)",
    )
    parser.add_argument(
        "--concurrency",
        type=int,
        default=16,
        help="Max concurrent evaluation tasks",
    )
    parser.add_argument(
        "--remote",
        action="store_true",
        help="Use remote LLM defined in local.json for evaluation",
    )
    parser.set_defaults(_handler=_handle_evaluate)


async def _process_single_item(
    item: dict, prediction_map: dict, evaluator: Evaluator, sem: asyncio.Semaphore
) -> ResultItem | None:
    """处理单个评估项"""
    async with sem:
        try:
            qid = item.get("questionId")
            if qid not in prediction_map:
                # 缺少预测结果
                return None

            pred_item = prediction_map[qid]
            prediction = pred_item.get("prediction")

            # 准备参考答案列表
            answer = item.get("answer", [])
            if isinstance(answer, str):
                answer = [answer]
            elif not isinstance(answer, list):
                # 针对复杂数据集（如 DUDE）的回退逻辑
                if "answers" in item:
                    answer = [", ".join(item["answers"])] + item.get(
                        "answers_variants", []
                    )
                else:
                    answer = []

            # AI 判定
            judge = "F"

            # 针对不可回答问题的特殊逻辑
            if item.get("answer_type") == "not-answerable":
                is_valid_ans = await evaluator.check_answer(
                    item["question"], prediction
                )
                if not is_valid_ans:
                    judge = "T"
                else:
                    judge = "F"
            else:
                judge = await evaluator.is_equal(item["question"], answer, prediction)

            # 构造 ResultItem
            result_item = ResultItem(
                questionId=qid,
                pdf_id=item.get("pdf_id", "")
                or str(item.get("image_id", "")),  # 回退到 image_id
                question=item["question"],
                answer=answer,
                tag=item.get("tag"),
                prediction=prediction,
                judge=judge,
            )
            return result_item

        except Exception as e:
            evaluator.logger.error(
                f"Error processing item {item.get('questionId')}: {e}"
            )
            return None


async def _run_evaluation(
    input_path: Path,
    result_path: Path,
    output_path: Path,
    concurrency: int,
    logger: logging.Logger,
    use_remote: bool = False,
):
    """运行批量评估流程"""
    settings = Settings.load()
    evaluator = Evaluator(settings, logger, use_remote=use_remote)

    # 加载数据集和预测结果
    with open(input_path, "r", encoding="utf-8") as f:
        dataset = json.load(f)

    with open(result_path, "r", encoding="utf-8") as f:
        results = json.load(f)

    # 将预测结果按 ID 映射，以便快速查找
    prediction_map = {r["questionId"]: r for r in results}

    sem = asyncio.Semaphore(concurrency)
    tasks = [
        _process_single_item(item, prediction_map, evaluator, sem) for item in dataset
    ]

    evaluated_items = []
    for f in tqdm(asyncio.as_completed(tasks), total=len(tasks), desc="Evaluating"):
        res = await f
        if res:
            evaluated_items.append(res)

    # 保存评估结果
    output_path.parent.mkdir(parents=True, exist_ok=True)
    write_results_file(str(output_path), evaluated_items)

    # 计算各项指标
    total = len(evaluated_items)
    correct = sum(1 for item in evaluated_items if item.judge == "T")
    accuracy = correct / total if total > 0 else 0.0

    anls_score = 0.0
    for item in evaluated_items:
        if item.judge == "T":

            contain = False
            if item.prediction:
                for ans in item.answer:
                    if ans and ans.lower() in item.prediction.lower():
                        contain = True
                        break

            if contain:
                anls_score += 1.0
            elif item.answer == [] or (
                item.prediction is None and item.judge == "T"
            ):  # 针对不可回答问题的近似处理
                anls_score += 1.0
            else:
                anls_score += evaluator.anls_single_sample(item.prediction, item.answer)
        else:
            anls_score += evaluator.anls_single_sample(item.prediction, item.answer)

    anls = anls_score / total if total > 0 else 0.0

    print("\nEvaluation Complete.")
    print(f"Total: {total}")
    print(f"Accuracy: {accuracy:.4f}")
    print(f"ANLS: {anls:.4f}")
    print(f"Detailed results saved to {output_path}")


def _handle_evaluate(args: argparse.Namespace, logger: logging.Logger) -> int:
    """evaluate 命令的处理器"""
    # 只有在不使用远程 LLM 时才确保本地 LLM 已加载
    if not args.remote:
        ensure_llm_local_loaded(Settings.load(), logger)
    try:
        asyncio.run(
            _run_evaluation(
                Path(args.input),
                Path(args.result),
                Path(args.output),
                args.concurrency,
                logger,
                use_remote=args.remote,
            )
        )
        return 0
    except Exception as e:
        logger.error(f"Evaluation failed: {e}")
        return 1
    finally:
        if not args.remote:
            shutdown_llm_local()
