import argparse
import asyncio
import json
import logging
from concurrent.futures import ThreadPoolExecutor, as_completed
from dataclasses import asdict
from pathlib import Path
from typing import Any, List

import Levenshtein
from tqdm import tqdm

from modora.core.domain.results import ResultItem
from modora.core.infra.llm.qwen import AsyncQwenLLMClient
from modora.core.infra.llm.remote import AsyncRemoteLLMClient
from modora.core.settings import Settings
from modora.core.infra.llm.process import ensure_llm_local_loaded, shutdown_llm_local

# --- Prompts ---
EVALUATION_PROMPT = """
### Instruction
Now there are the Reference answer and the generated answer to a query. Please judge whether the generated answer is correct according to the reference, output T if correct, otherwise output F.
Please mainly focuses on whether the semantics of the answers to the key parts of the query are consistent, and allows differences in the degree of detail, the sentence pattern, and the format of answers.

### Reference Answer
{a}

### Generated Answer
{b}

### Note
You only need to output T or F, without any other content.
"""

CHECK_ANSWER_PROMPT = """
### Instruction
Here is a query and a reply to it. Please return T or F according to the following rules:
(1) If the reply refuses to give a valid answer by meanings like "no relevant information", "insufficient evidence", "unable to answer", "None", "N/A", output F.
(2) Otherwise output T.

### Query
{query}

### Reply
{answer}

### Note
You only need to output T or F, without any other content.
"""


class Evaluator:
    def __init__(self, settings: Settings, logger: logging.Logger, use_remote: bool = False):
        self.settings = settings
        self.logger = logger
        if use_remote:
            self.llm = AsyncRemoteLLMClient(settings)
        else:
            self.llm = AsyncQwenLLMClient()

    async def _bool_string(self, s: str) -> bool:
        s = s.lower()
        if "true" in s or "t" in s or "yes" in s or "y" in s or "1" in s or "on" in s:
            return True
        return False

    async def check_answer(self, query: str, answer: str) -> bool:
        prompt = CHECK_ANSWER_PROMPT.format(query=query, answer=answer)
        try:
            res = await self.llm.generate_text(prompt)
            return await self._bool_string(res)
        except Exception as e:
            self.logger.error(f"Error in check_answer: {e}")
            return False

    async def is_equal(self, query: str, references: List[str], prediction: str) -> str:
        if not prediction:
            return "F"
        
        for reference in references:
            # Containment Check
            if reference.lower() in prediction.lower():
                return "T"

            # AI Check
            prompt = EVALUATION_PROMPT.format(query=query, a=reference, b=prediction)
            try:
                res = await self.llm.generate_text(prompt)
                if "T" in res:
                    return "T"
            except Exception as e:
                self.logger.error(f"Error in is_equal AI check: {e}")
                
        return "F"

    def anls_single_sample(self, prediction: str, references: List[str], threshold: float = 0.5) -> float:
        max_nls = 0.0
        pred_str = prediction if prediction is not None else ""
        
        for reference in references:
            distance = Levenshtein.distance(pred_str, reference)
            max_len = max(len(pred_str), len(reference))
            if max_len == 0:
                nls = 1.0
            else:
                nls = 1.0 - float(distance) / max_len
            
            if nls > max_nls:
                max_nls = nls

        return max_nls if max_nls > threshold else 0.0


def register(sub: argparse._SubParsersAction) -> None:
    parser = sub.add_parser("evaluate", help="Evaluate QA results")
    parser.add_argument(
        "--input",
        default = "/home/yukai/project/MoDora/datasets/MMDA/test.json",
        help="Path to the input JSON file (original dataset)",
    )
    parser.add_argument(
        "--result",
        default = "/home/yukai/project/MoDora/MoDora-backend/tmp/result.json",
        help="Path to the result JSON file (generated by batch-qa)",
    )
    parser.add_argument(
        "--output",
        default = "/home/yukai/project/MoDora/MoDora-backend/tmp/evaluation.jsonl",
        help="Path to save the evaluation report (JSONL)",
    )
    parser.add_argument(
        "--concurrency",
        type=int,
        default=16,
        help="Max concurrent evaluation tasks",
    )
    parser.add_argument(
        "--remote",
        action="store_true",
        help="Use remote LLM defined in local.json for evaluation",
    )
    parser.set_defaults(_handler=_handle_evaluate)


async def _process_single_item(
    item: dict, 
    prediction_map: dict, 
    evaluator: Evaluator, 
    sem: asyncio.Semaphore
) -> ResultItem | None:
    async with sem:
        try:
            qid = item.get("questionId")
            if qid not in prediction_map:
                # Missing prediction
                return None

            pred_item = prediction_map[qid]
            prediction = pred_item.get("prediction")
            
            # Prepare answer list
            answer = item.get("answer", [])
            if isinstance(answer, str):
                answer = [answer]
            elif not isinstance(answer, list):
                # Fallback for complex datasets like DUDE
                if "answers" in item:
                     answer = [", ".join(item["answers"])] + item.get("answers_variants", [])
                else:
                    answer = []
            
            # AI Judgment
            judge = "F"
            
            # Special logic for unanswerable
            if item.get("answer_type") == "not-answerable":
                is_valid_ans = await evaluator.check_answer(item["question"], prediction)
                if not is_valid_ans:
                    judge = "T"
                else:
                    judge = "F"
            else:
                judge = await evaluator.is_equal(item["question"], answer, prediction)

            # Construct ResultItem
            result_item = ResultItem(
                questionId=qid,
                pdf_id=item.get("pdf_id", "") or str(item.get("image_id", "")), # Fallback for image_id
                question=item["question"],
                answer=answer,
                tag=item.get("tag"),
                prediction=prediction,
                judge=judge
            )
            return result_item

        except Exception as e:
            evaluator.logger.error(f"Error processing item {item.get('questionId')}: {e}")
            return None


async def _run_evaluation(
    input_path: Path, result_path: Path, output_path: Path, concurrency: int, logger: logging.Logger, use_remote: bool = False
):
    settings = Settings.load()
    evaluator = Evaluator(settings, logger, use_remote=use_remote)
    
    # Load Data
    with open(input_path, "r", encoding="utf-8") as f:
        dataset = json.load(f)
    
    with open(result_path, "r", encoding="utf-8") as f:
        results = json.load(f)
    
    # Map predictions by ID for fast lookup
    prediction_map = {r["questionId"]: r for r in results}
    
    sem = asyncio.Semaphore(concurrency)
    tasks = [
        _process_single_item(item, prediction_map, evaluator, sem)
        for item in dataset
    ]
    
    evaluated_items = []
    for f in tqdm(asyncio.as_completed(tasks), total=len(tasks), desc="Evaluating"):
        res = await f
        if res:
            evaluated_items.append(res)

    # Save Results
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        for item in evaluated_items:
            f.write(json.dumps(item.to_dict(), ensure_ascii=False) + "\n")

    # Calculate Metrics
    total = len(evaluated_items)
    correct = sum(1 for item in evaluated_items if item.judge == "T")
    accuracy = correct / total if total > 0 else 0.0
    
    anls_score = 0.0
    for item in evaluated_items:
        if item.judge == "T":
            
            contain = False
            if item.prediction:
                for ans in item.answer:
                    if ans and ans.lower() in item.prediction.lower():
                        contain = True
                        break
            
            if contain:
                anls_score += 1.0
            elif item.answer == [] or (item.prediction is None and item.judge == "T"): # Unanswerable logic approximation
                 anls_score += 1.0
            else:
                 anls_score += evaluator.anls_single_sample(item.prediction, item.answer)
        else:
             anls_score += evaluator.anls_single_sample(item.prediction, item.answer)

    anls = anls_score / total if total > 0 else 0.0

    print(f"\nEvaluation Complete.")
    print(f"Total: {total}")
    print(f"Accuracy: {accuracy:.4f}")
    print(f"ANLS: {anls:.4f}")
    print(f"Detailed results saved to {output_path}")


def _handle_evaluate(args: argparse.Namespace, logger: logging.Logger) -> int:
    # Only ensure local LLM loaded if NOT using remote
    if not args.remote:
        ensure_llm_local_loaded(Settings.load(), logger)
    try:
        asyncio.run(_run_evaluation(
            Path(args.input), 
            Path(args.result), 
            Path(args.output), 
            args.concurrency, 
            logger,
            use_remote=args.remote
        ))
        return 0
    except Exception as e:
        logger.error(f"Evaluation failed: {e}")
        return 1
    finally:
        if not args.remote:
            shutdown_llm_local()
